/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

import { TransitionHandlerProps } from '@bit/mui-org.material-ui.internal.transitions/dist/transition';
export { TransitionHandlerProps };
import { TransitionProps } from '@bit/mui-org.material-ui.internal.transitions/dist/transition';
export { TransitionProps };